## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

branches:
  only:
    - master

notifications:
  email: false

git:
  depth: 99999999

jobs:
  allow_failures:
    - julia: nightly
    - os: osx  # travis timing out
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.build() '
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Garamond"));
              using Coverage;
              Coveralls.submit(process_folder());
              Codecov.submit(process_folder())'
